orm-final-101/dalim_api

accounts/serializers.py, config/settings.py
rest_auth의 user_details_serializer 오버라이딩
=> feature/#9 :sparkles: 로그인 시 반환하는 유저 정보 커스텀

boards/models.py
1. models.py 완성 
2. serializers.py 생성
=> Feature:#17 :wrench: model 수정 및 serializer 생성

config/constants.py, crews/admin.py, crews/models.py, crews/permissions.py, crews/serializers.py, crews/tests.py, crews/urls.py, crews/views.py, races/models.py
- models.py
- blank=True 제거
- serializers.py
- views.py
- permissions.py (review 권한 관련)
- urls.py
- constants.py
- 유저의 status 부분 속성 추가 `("quit", "탈퇴")`
=> Feature/#27 ✨ crews 앱 기능 구현 및 관련 코드 수정

accounts/models.py, accounts/serializers.py, accounts/urls.py, accounts/views.py, promotions/models.py, races/models.py
[urls.py] [views.py]
- fbv로 작성
GET	/accounts/mypage/info	회원정보
PATCH	/accounts/mypage/info	회원정보 수정
- 뷰셋으로 작성
GET	/accounts/mypage/record	달린 기록 보기
POST	/accounts/mypage/record	달린 거리 기록하기
PATCH	/accounts/mypage/record/<int:record_id>	달린 거리 수정하기
DELETE	/accounts/mypage/record/<int:record_id>	달린 거리 삭제하기
[models.py]
- accounts, promotion 모델 blank=True 제거
[etc]
- races 모델의 setting import 수정은 민경 커밋으로 이미 메인에 들어가있음.
=> Feature/#28 #32 ✨ 회원정보, 달림기록 API 작성

races/admin.py, races/models.py
=> feature/#41 :wrench: 대회앱 admin, models 수정

accounts/models.py, accounts/serializers.py, accounts/urls.py, accounts/views.py
GET	/accounts/mypage/race	내가 신청한 대회 내역
POST	/accounts/mypage/race	내가 신청한 대회 내역 추가
PATCH	/accounts/mypage/race/<int:joined_race_id>	내 대회 기록 추가/수정하기
DELETE	/accounts/mypage/race/<int:joined_race_id>	내 대회 기록 삭제하기
작업 과정에서 URL 테이블과 response 상세 수정 있었음
=> :sparkles: Feature/#37 내가 신청한 대회내역 추가, 대회기록 API 뷰셋 작성

boards/admin.py, boards/apps.py, boards/models.py, boards/urls.py, boards/views.py
1. #@api_view(['GET','POST']) 해당 주석 지우면 is_liked = False 으로 변하지 않음, 문의 예정
2. makemigrations 문제 -> boards/admin.py 의 안 쓰는 모듈 삭제
3. 따옴표 -> 쌍따옴표 변경
=> 🐛 makemigrations, like_post 버그 수정

config/constants.py, crews/serializers.py, crews/tests.py, crews/urls.py, crews/views.py
- views.py
- urls.py
- serializers.py
- 은선님 오픈프로필 코드 추가
- tests.py
→ viewset으로 변환
- constants.py
- 쌍따옴표 컨벤션 맞춤
=> Feature/#29 🎨 crews 앱 FBV → viewset으로 변환, 테스트코드 수정

races/models.py, races/serializers.py, races/urls.py, races/views.py
=> Feature/#60 🔧 대회목록조회/GET 

crews/permissions.py, crews/views.py
- views.py
- 모집중(`"is_opened": True`)인 크루에서만 뽑도록 수정
- permissions.py
- 줄바꿈 컨벤션 맞춤
=> Feature/#64 🔧 crews top6 기능 수정 및 컨벤션 맞춤

races/serializers.py, races/urls.py, races/views.py
=> feature/#66 :wrench: 대회 상세 / GET

crews/urls.py
=> Feature/#71 🚑 crews url 수정

crews/models.py, crews/serializers.py, crews/tests.py, crews/urls.py, crews/views.py
- views.py
- `extend_schema`추가
=> ✨ Feature/#75 crews 앱 extend_schema 추가

races/models.py, races/serializers.py, races/urls.py, races/views.py
feature/#69 
feature/#80
feature/#81
feature/#82
feature/#83
feature/#84
feature/#35
모두 포함하였습니다.
=> :sparkles: feature/#69, #80, #81, #82, #83, #84, #35

README.md
틀만 적어놨습니다. 맡으신 목차에 따라 작성해주시면 됩니다.
=> 📝 Feature/#92 README 구조 setup

boards/models.py, boards/serializers.py, boards/urls.py, boards/views.py
1. 상세보기 문제 해결
2. 쿼리스트림 문제 해결
3. like_post 문제 해결 
------
그 다음 해야 할 항목 진행할 사항
1. boards 권한 정리 및 작업 
2. Delete post/{post_id} 할 때 
json response로 
{
"message": "게시글을 삭제했습니다"
}
메세지 나타내기 
-----
=> Feature/#79 boards api 작업 완료 

boards/admin.py, boards/models.py, boards/permissions.py, boards/serializers.py, boards/urls.py, boards/views.py, config/constants.py
권한 작업 중 POST /boards에서 is_staff 
- category는 is_staff와 상관 없이 선택 가능
- post_classification를 선택한 경우 이벤트랑 공지글 작성하시는 작성자가 is_staff 이어야 한다.
-
이건 확인 못했음 
모델 Category, Post_classification 삭제 및 수정 
Post_classification announcement-> notice 수정
=> Feature/#95 ✨ Delete시 메세지 출력, 권한 작업 🎨 serializers.py 코드 경량화 🔧 모델 수정 및 category api 만들기

boards/serializers.py, boards/urls.py, boards/views.py
1. comment CRUD 완료 
개선 예정 : 
본인이 작성한 댓글이 다른 유저가 수정 삭제 하는 버그
=> Feature/#98 ✨ Comment Api 작업 완료

races/tests.py
=> :white_check_mark: feature/#88 대회 앱 tests.py

races/serializers.py, races/tests.py
=> :bug: feature/#105 대회 코스 데이터 1개일때도 리스트로 반환

races/serializers.py, races/views.py
=> :bug: feature/#107 대회 리뷰 API 수정 - "author_nickname"

boards/models.py, boards/permissions.py, boards/serializers.py, boards/views.py
1. 게시글이 최근 작성된 글이 맨 위로 오도록 정렬 수정
- PostListSerializer > Meta에 order_by  넣음
2. 해당 API 요청할 때 마다 view_count가 증가해야 하는데 증가하지 않음
- 관련 함수 ViewSet으로 옮김
3. 사용자의 좋아요 여부와 상관 없이 likes의 is_liked가 항상 false로 들어옴
- PostDetailSerializer > get_likes 수정
4. Post 모델의 thumbnail_images의 "default_thumbnail_image" 부분 삭제
- 삭제하였습니다
5. 게시글 작성 POST 날릴 때 response에 생성된 post의 id를 담음
- PostCreateSerializer > to_representation 함수 작성
6. post_classification, category가 숫자로 들어옴 "general", "trainning"같은 스트링으로 수정
- PostCreateSerializer > serializers.ChoiceField 사용 
--------------------------
다른 작업
**_권한 작업 완료_** 
Post, Comment 관련한 권한 작업 완료했습니다. 
이에 대한 테스트도 완료했습니다
=> feature/#110 :bug: board 요청 사항 수정

crews/serializers.py
=> 🐛 Feature/#117 member_count 필드 자료형 변환

crews/serializers.py
=> 🚑 Feature/#120 member_count 필드 복원

crews/serializers.py
=> 🐛 Feature/#122 멤버관리 serializer 수정

crews/serializers.py, crews/tests.py, crews/urls.py, crews/views.py
- views.py
- urls.py
- serializers.py
=> 🎨 Feature/#128 코드 구조 수정, 주석 추가

README.md
=> :wrench: ERD 넣기

crews/views.py
- 요일 필터링을 AND 조건으로 변경
- 크루 관리자 페이지에서 크루 리스트를 id기준 내림차순으로 정렬
=> 🔧 Feature/#143 요일 필터링, 크루 리스트 정렬 수정

crews/serializers.py, crews/views.py
- 이미지 필드가 `"None"`이 되지 않도록 partial 파라미터값을 `True`로 설정.
- 크루 생성 시 `is_opened=True` 지정
=> 🐛 Feature/#152 크루 수정 시 이미지필드 처리, 모집여부 수정

crews/tests.py
- `test_filter_by_multiple_meet_days` 테스트 함수 수정
- 실제 기능상의 변경은 없습니다.
=> ✅ Feature/#154 요일 필터링 파트 수정

README.md
Feature/#151 readme erd 변경 및 내용 수정
=> Feature/#151 📝 readme erd 변경 및 내용 수정

README.md
=> 📝 Feature/#162 메서드 수정

README.md
=> :memo: 리드미 마이너 수정

crews/admin.py
- 크루장이거나 스태프권한이 있는 회원만 선택할 수 있도록 수정함.
- 주석 추가
=> 🎨 Feature/#170 크루 생성시 owner 조건 추가

README.md
=> readme 오타 수정

accounts/serializers.py, accounts/views.py
joinedCrew, joinedRace 사용하는 serializer에서 썸네일 이미지 path로 리턴하는 현상 있음
serializer에서 썸네일 이미지의 절대url을 생성해서 리턴하도록 수정
=> :wrench: joinedCrew, joinedRace에서 썸네일 이미지 path -> url 리턴하도록 수정
